### ISSUE TITLE
Контроль температуры и влажности - Поддержка работы с датчиком BME280

### ISSUE THREAD

**Issue by avfc1874** [oleg-milantiev/allsky.py#10]
Требуется обеспечить возможность подключения и получения данных с Датчика марки BME280, размещаемого в подкупольном пространстве устройства AllSky-камера.

**Comment by oleg-milantiev** [comment]
Готово. В рамках https://github.com/oleg-milantiev/allsky.py/blob/master/bme280.todb.py

**Comment by oleg-milantiev** [comment]
Данные попадают в базу. Таблица sensor

**Comment by avfc1874** [comment]
Спасибо!
Обратил внимание, что на странице "Графики" веб-приложения AllSky появилась возможность просмотра диаграммы.
Но пока не совсем понятны выводимые значения.

**Comment by oleg-milantiev** [comment]
Ага, делаю.
Пока там fake из примера.

**Comment by oleg-milantiev** [comment]
Решено в разделе Графики / Сенсоры
