### ISSUE TITLE
Docker образ

### ISSUE THREAD

**Issue by oleg-milantiev** [oleg-milantiev/allsky.py#102]
Для простоты развёртывания собрать и настроить докер-образ с пробросом камеры в него.

**Comment by avfc1874** [comment]
Хм. Извиняюсь, но не знаю, что такое Docker!
Какую практическую задачу (создания/отладки/макетирования стенда/ПО или иное) предполагается с помощью этого Dockera решить?

**Comment by oleg-milantiev** [comment]
Что-то отдалённо напоминающее виртуальную машину. Уже настроенную.
Это не совсем то же самое, но очень похоже. В идеале, описание установки, после перехода на Docker, сократится до двух строк:
- wget какой-то-адрес/install.sh
- ./install.sh

То есть речь о создании инсталятора (другая задача). Но, чтобы его сделать, сначала нужно СИЛЬНО упростить процедуру развёртывания. Докер в этом мастер!

**Comment by avfc1874** [comment]
> Что-то отдалённо напоминающее виртуальную машину. Уже настроенную. Это не совсем то же самое, но очень похоже. В идеале, описание установки, после перехода на Docker, сократится до двух строк:
> 
> * wget какой-то-адрес/install.sh
> * ./install.sh
> 
> То есть речь о создании инсталятора (другая задача). Но, чтобы его сделать, сначала нужно СИЛЬНО упростить процедуру развёртывания. Докер в этом мастер!

Большое Спасибо! Отлично!

**Comment by oleg-milantiev** [comment]
Было интересно. Недельку провозился. Что-то решил, но осталось ещё больше проблем :)
Задача объёмная, снаскоку не решить.

Для истории - контейнер создал, в нём собрал всё с нуля и в нём allsky.py со всеми зависимости работает. Но, возможно, экономней будет использовать чужие сборки, например так https://github.com/tepickering/indi-docker/blob/master/Dockerfile.rpi
Версию только обновить. Хочется свежий python с match :) (от 3.10).

Из оставшихся задач:
- тест с реальным железом, возможно надо будет добавить Starlight драйвер;
- начал тестировать QHY, понял что нужна fxload с типом fx3;
- опять таки, QHY - udev или какой-то иной способ загрузки firmware;
- ffmpeg и герман - ещё два простых ящика;
- автоматическое обновление / генерация конфига из python в json и дальше в php. Кстати, может через sync германа?
- инсталятор, чтобы сам камеру определял и вписывал в конфиг (мечты?) или, как минимум, восстановить работу list.py, как раньше;
- веб начал запускать, доделать. Тут просто всё, так что на потом;

**Comment by oleg-milantiev** [comment]
Ветка на паузе. Контейнер собрал норм. Камеру видит. Но кадры не приходят.
В чём дело, пока не понял.

**Comment by oleg-milantiev** [comment]
Движение вперёд!

Получилось собрать работающие контейнеры QHY и ZWO без использования INDI.
Планирую собрать компоненты docker-compose с использованием RabbitMQ.

**Comment by oleg-milantiev** [comment]
Собрал работающий прототип, решил описать структурную схему докер-сборки.

Связующие элементы:
- в центре стоит менеджер очереди [RabbitMQ](https://www.rabbitmq.com/) (официальный готовый докер-контейнер). Всё общение меж компонент комплекса ведётся через него;
- MySQL СУБД (стандартный docker контейнер). При первом запуске создаёт базу и заливает дамп.

Backend (фоновая) часть:
- camera контейнер. Один из выбранных контейнеров: QHY, ZWO, SX, ... в них сборка из [RabbitMQ RPC сервера](https://github.com/rabbitmq/rabbitmq-tutorials/blob/main/python/rpc_server.py) и python-binding SDK конкретного производителя: [QHY](https://github.com/JiangXL/qhyccd-python), ZWO, SX. Задача этого контейнера слушать rabbit очередь и выполнять команды получения кадра по заданным gain / exposure;
- allsky контейнер. Небольшой python скрипт, единственная задача которого, через rabbit и worker в контейнере camera, делать снимки и подбирать выдержку, gain, bin в заданных рамках. Для обработки (через rabbit) вызывает process;
- process контейнер. Получает задачи от allsky контейнера. Обрабатывает fit, делает jpg;
- tbd video (опишу чуть позже - то, что делает видео);
- tbd tmpwatch (опишу чуть позже - то, что чистит архивы);
- tbd watchdog (опишу чуть позже - то, что следить за стабильной работой комплекса).

Веб:
- nginx (стандартный docker контейнер);
- php-fpm (build с добавлением sql и rabbit модулей из стандартного docker контейнера).

**Comment by oleg-milantiev** [comment]
Запустил две сборки:
- x64 + QHY5 старая шайба
- arm64 (orange pi 3 lts) + ZWO 290

Работают :)

Начал сливать master в ветку docker.

**Comment by oleg-milantiev** [comment]
Решено. Пока что в отдельной ветке docker.
Ветка master больше не поддерживается и скоро будет замещена веткой docker.
