### ISSUE TITLE
Яндекс-счетчик на сайт

### ISSUE THREAD

**Issue by flyeye** [oleg-milantiev/allsky.py#104]
Хочется видеть статистику кто пользуется камерой.

**Comment by oleg-milantiev** [comment]
Ты про https://allsky.milantiev.com/ ?
Или про локальный веб, что на малине / апельсине?

**Comment by flyeye** [comment]
Про локальный веб на малине/апельсине

**Comment by oleg-milantiev** [comment]
А как на него заходят пользователи? Ты прокидываешь его наружу?

**Comment by flyeye** [comment]
Ага.

**Comment by oleg-milantiev** [comment]
![image](https://user-images.githubusercontent.com/15366972/230727440-338de4c3-1b12-4527-88dd-bb61cec8551f.png)

**Comment by flyeye** [comment]
Установил, работает! Спасибо!
