### ISSUE TITLE
Зацикливание при подборе выдержки

### ISSUE THREAD

**Issue by flyeye** [oleg-milantiev/allsky.py#106]
Иногда возникает ситуация, когда камера впадает в состояние зацикливания при подборе выдержки. По видимому, проблема в округлении выдержки уже при передачи параметра в камеру.
Например: 
![image](https://user-images.githubusercontent.com/8995495/230560462-b85714db-08ee-4af9-8d5f-6883c18593bd.png)
Камера имеет минимальную выдержку 0.0001. Подозреваю, что 0.00027 она принимает как 0.0003, а 0.00022 как 0.0002. И в итоге прыгает вокруг заданного интервала допустимых значений среднего туда-сюда, хотя интервал вроде бы не маленький... 19000-25000.

**Comment by oleg-milantiev** [comment]
Я думаю, нужно ввести ограничение на максимальное кол-во повторов. 10 раз попрыгал туда-сюда, дал кадр. В следующую минуту подберёт лучше.

Основная задача камеры - снимать сцену в условиях небольших плавных изменений освещённости. А не гоняться за самой лучшей экспозицией, отличающейся в разы от прошлой.

**Comment by flyeye** [comment]
Сделал, и округление до нужного знака после запятой, и подсчет количества попыток подобрать экспозицию. Пока в ветке CCDGain. Тестирую у себя, после закоммичу и сделаю пулреквест.

**Comment by oleg-milantiev** [comment]
В ветке docker полностью (масштабно) переделана процедура подбора выдержки. Зацикливания больше нет.
