### ISSUE TITLE
Мониторинг платформы

### ISSUE THREAD

**Issue by flyeye** [oleg-milantiev/allsky.py#107]
Хочется куда-то собирать и где-то видеть данные по температуре процессора, свободному пространству на диске, загрузке процессора, загрузке сетевого интерфейса. Не уверен, что все нужно вытаскивать в веб, может быть заббикс какой прикрутить.
Пока идея на будущее.

**Comment by oleg-milantiev** [comment]
Zabbix прикрутил. И развиваю колво показателей / тригеров.
https://github.com/oleg-milantiev/allsky.py/issues/115

Закрываю, как дублирующий
