### ISSUE TITLE
Контроль температуры и влажности - Отображение текущих значений температуры и влажности под куполом AllSky-камеры

### ISSUE THREAD

**Issue by avfc1874** [oleg-milantiev/allsky.py#11]
На главной странице Системы должна выводиться информация о текущих значениях температуры и влажности, полученных с датчика BME280, расположенного в подкупольном пространстве Устройства AllSky-камера.

**Comment by oleg-milantiev** [comment]
Решено в разделе Графики / Сенсоры

**Comment by oleg-milantiev** [comment]
попутал задачи. Ещё на главную не вывел. Переоткрываю

**Comment by oleg-milantiev** [comment]
Дубль. Решено
