### ISSUE TITLE
Главная страница AllSky - Автообновление страницы

### ISSUE THREAD

**Issue by avfc1874** [oleg-milantiev/allsky.py#12]
Обеспечить автоматическое автообновление страницы каждые 60 сек.

**Comment by oleg-milantiev** [comment]
Сделал автообновление с управление чекбоксом. Он включен - обновляется раз в минуту. Выключен - не обновляется.

Чекбокс расположен на главной, справа-сверху, в строке "сейчас ............." под "вход".
