### ISSUE TITLE
Оповещение пользователя о "хорошем небе" посредством электронного уведомления

### ISSUE THREAD

**Issue by avfc1874** [oleg-milantiev/allsky.py#122]
Необходимо обеспечить настройку значения "Хорошее" количество звезд и использование его для автоматического оповещения пользователя о достижении такого значения посредством ТГ канала или иным способом.

**Comment by oleg-milantiev** [comment]
Добавлю, что нужно учитывать наличие и фазу Луны. Т.к. 100 звёзд при Луне - это чистое небо. А 100 звёзд без неё - это пора думать, не закрыть ли крышу.

**Comment by oleg-milantiev** [comment]
Связана с https://github.com/oleg-milantiev/allsky.py/issues/123 и заблокирована ей

**Comment by oleg-milantiev** [comment]
Поглощена задачей https://github.com/oleg-milantiev/allsky.py/issues/123
