### ISSUE TITLE
Аннотации (наложение текста) - вывод числового значения с плавающей точкой до 4 знаков после запятой

### ISSUE THREAD

**Issue by avfc1874** [oleg-milantiev/allsky.py#124]
Желательно для Аннотации (наложение текста), которая формируется на основании числового значения с плавающей точкой реализовать вывод на экран до 4 знаков после запятой.

**Comment by oleg-milantiev** [comment]
Видимо, ты про вывод exposure. В ней 4 знака норм.
В AI* я уже сократил до 2 знаков.

**Comment by avfc1874** [comment]
> Видимо, ты про вывод exposure. В ней 4 знака норм. В AI* я уже сократил до 2 знаков.

Посмотри пожалуйста отображение "CCD avg" по адресу: [http://allsky.vega2017.keenetic.link/](http://allsky.vega2017.keenetic.link/)

**Comment by oleg-milantiev** [comment]
А вот гляди. Exp понятно, там нужно 4 знака, т.к. минималка 0.001.
А зачем 4 знака в avg? Мне кажется, там вовсе дробные не имеют смысла.
