### ISSUE TITLE
Управление цепью подогрева подкупольного пространства - Поддержка работы с мосфетом марки IRF520 MOS

### ISSUE THREAD

**Issue by avfc1874** [oleg-milantiev/allsky.py#13]
Обеспечить возможность подключения мосфета марки IRF520 MOS для управления цепью подогрева подкупольного пространства.

**Comment by avfc1874** [comment]
Мосфеты в наличии и готовы для апробации.

**Comment by avfc1874** [comment]
Вероятно этот запрос следует закрыть, как неактуальный.

**Comment by oleg-milantiev** [comment]
ага, запустим с другим железом
