### ISSUE TITLE
Управление цепью подогрева подкупольного пространства - Включения/выключение подогрева в ручном режиме

### ISSUE THREAD

**Issue by avfc1874** [oleg-milantiev/allsky.py#14]
Обеспечить возможность пользователю с правами администратор включать/выключать подогрев подкупольного пространства.

**Comment by avfc1874** [comment]
Вероятно придется продумать возможность входа в систему с правами Владельца - Администратора.
Пользователю с этой ролью становятся доступным операции включение подогрева/выключения подогрева

**Comment by oleg-milantiev** [comment]
Вынес авторизацию в отдельный issue

**Comment by avfc1874** [comment]
Реализовано.
