### ISSUE TITLE
Главная страница - Наличие ссылки на последний mp3-ролик

### ISSUE THREAD

**Issue by avfc1874** [oleg-milantiev/allsky.py#16]
Обеспечить на главной странице отображение ссылки на последний mp4-ролик, который был создан системой с указанием даты и времени его создания.

**Comment by avfc1874** [comment]
исправил mp3 на mp4

**Comment by oleg-milantiev** [comment]
К слову сказать, запись звука - очень интересная опция для AllSky. В т.ч. в качестве косвенного детектора дождя / ветра.

Я планировал в своей обсерватории записывать звук под металлической крышей. Использовать его как датчик дождя. Даже мелкие капли очень хорошо детектируются многократным (и длительным) увеличением уровня в микрофоне.

**Comment by avfc1874** [comment]
Интересно, но мне кажется избыточно. У меня есть IP-камера со встроенным микрофоном. Лежит в коробочке на даче. Никак не придумаю куда ее поставить :)

**Comment by oleg-milantiev** [comment]
Готово
