### ISSUE TITLE
Вёрстка, красивости

### ISSUE THREAD

**Issue by oleg-milantiev** [oleg-milantiev/allsky.py#18]
Вёрстка "сайта" allsky камеры. Бутстрап и прочее нужное и современное.

**Comment by avfc1874** [comment]
Это хорошее требование, но наверное это Шаблоны страниц:
- Главная
- Авторизация
- Статистика показаний датчиков

**Comment by oleg-milantiev** [comment]
Ввиду отсутствия чёткого ТЗ, состав страниц будет пополняться по мере расширения функционала (эволюционный рост). Поэтому, в рамках этой задачи, нужно дать каркас / обёртку / шаблон для всех страниц.

**Comment by avfc1874** [comment]
Предложенный концептуальный вариант веб-приложения в виде Панели управления будет удобен.

https://getbootstrap.com/docs/4.3/examples/dashboard/
"...Изначально кадр AllSky на экране. Слева можно выбрать другой раздел, появились архив и данные датчиков. В т.ч. графики..."

**Comment by oleg-milantiev** [comment]
Шаблон применил. Остальное по мере развития проекта
