### ISSUE TITLE
Мобильный браузер - Сделать отображение Меню на Главной странице

### ISSUE THREAD

**Issue by avfc1874** [oleg-milantiev/allsky.py#19]
Проверил возможность просмотра с использованием мобильного браузера.
К сожалению Меню для выбора разделов "Архив" и "Графики" не отображается.
Скриншот во вложении.

![screenshot_20190307-123155](https://user-images.githubusercontent.com/34251661/53946812-93006880-40d5-11e9-8504-8eb99bb78705.jpg)

**Comment by oleg-milantiev** [comment]
Готово. Но под мобилу ещё нужно улучшать отображение.
Пока что вся разработка с прицелом / проверкой на компе в первую очередь. Мобила на сдачу.

**Comment by avfc1874** [comment]
Спасибо! Отлично! Без "мобилы" уже никуда.
