### ISSUE TITLE
Запись в БД - Фиксация значений T/H при включении/выключении подогрева

### ISSUE THREAD

**Issue by avfc1874** [oleg-milantiev/allsky.py#20]
В БД требуется записывать информацию о времени включения/выключения подогрева, а также текущих значениях температуры и влажности в подкупольном пространстве.

**Comment by oleg-milantiev** [comment]
Как теперь, с учётом введённого % обогрева, поступить? Обогрев включается / выключается каждую минуту. Данные влажности / температуры будут не презентативны.

**Comment by avfc1874** [comment]
Требование предлагаю считать неактуальным. Закрываю.
