### ISSUE TITLE
Отбор данных из БД - Информации о количестве вкл/выкл подогрева и средних значениях T и H

### ISSUE THREAD

**Issue by avfc1874** [oleg-milantiev/allsky.py#21]
Требуется обеспечить вывод информации о количестве выполненных операций вкл/выкл подогрева, а также средних значениях температуры и влажности за текущие сутки, неделю, месяц.

**Comment by oleg-milantiev** [comment]
т.к. нет внешнего термодатчика, то регулирую процент включения обогрева.
Сделал веб часть регулятора на странице настроек: https://github.com/oleg-milantiev/allsky.py/wiki/web-settings

Делаю демоническую часть

**Comment by oleg-milantiev** [comment]
Готово
