### ISSUE TITLE
Автоудаление "горячих" пикселей с изображения

### ISSUE THREAD

**Issue by avfc1874** [oleg-milantiev/allsky.py#28]
Требуется обеспечить автоматическое удаление "горячих" пикселей с изображения, которое подлежит сохранению в системе.

**Comment by oleg-milantiev** [comment]
Связано с https://github.com/oleg-milantiev/allsky.py/issues/29

**Comment by oleg-milantiev** [comment]
Реализовал, подробности здесь: https://github.com/oleg-milantiev/allsky.py/wiki/Hot-Pixel
