### ISSUE TITLE
Возможность сохранить "темновой" кадр

### ISSUE THREAD

**Issue by avfc1874** [oleg-milantiev/allsky.py#29]
Для реализации функции автоудаления "горячих" пикселей у Администратора должна быть возможность загрузки и сохранения в Системе эталонного "темного" кадра.

**Comment by oleg-milantiev** [comment]
Связано с https://github.com/oleg-milantiev/allsky.py/issues/28

**Comment by oleg-milantiev** [comment]
Файл с битьём (не совсем дарк, скорее маска битых пикселей), пока что не через веб, но можно закинуть в /opt/allsky.py/camera/common/hot-{bin}.png.
Подробности здесь: https://github.com/oleg-milantiev/allsky.py/wiki/Hot-Pixel
