### ISSUE TITLE
AllSky Панель администрирования - Старт/Стоп сервиса AllSky  в "ручном" режиме

### ISSUE THREAD

**Issue by avfc1874** [oleg-milantiev/allsky.py#30]
Желательно, чтобы Администратор имел возможность на странице в Панели администрирования принудительно ( в ручном режиме) остановить/возобновить работу сервиса "AllSky".

**Comment by oleg-milantiev** [comment]
А когда это может понадобиться?

**Comment by avfc1874** [comment]
Предполагаю. Вероятно это позволит корректно возобновит работу после редактирования параметров.

**Comment by oleg-milantiev** [comment]
А.., понял.
Лучше заложить возможность автоматической загрузки параметров по их изменению, я думаю. Но стоп / старт проще реализовать. Пока начнём с него.

**Comment by avfc1874** [comment]
Если это требование повторяет текущую концепцию реализации, то можно его закрыть "как неактуальное".
