### ISSUE TITLE
favicon.ico - Наличие и отображение ее в заголовке окна веб-браузера

### ISSUE THREAD

**Issue by avfc1874** [oleg-milantiev/allsky.py#31]
Желательно в каталоге веб-приложения иметь файл favicon.ico, который иллюстрирует AllSky-камеру.
Требуется настроить отображение иконки в заголовке окна веб-браузера.

**Comment by oleg-milantiev** [comment]
А можешь плиз помочь с иконкой? Нарисовать её в ico-формате? На твой вкус.

**Comment by avfc1874** [comment]
ОК! Поищу.

**Comment by avfc1874** [comment]
Иконки-кандидаты:
- https://lh3.ggpht.com/-zmogwPmrnUN-YLt4oZlZqQqnmyqb9KJg-EWU-B26afimIaqWnREZ07T82heBk40cjs=w32
- http://machocolatiere.com/img/WorldMap-32.png

**Comment by avfc1874** [comment]
Требование не актуально.
