### ISSUE TITLE
Информация о месторасположении AllSky-камеры

### ISSUE THREAD

**Issue by avfc1874** [oleg-milantiev/allsky.py#33]
Опционально.
Администратор, при необходимости имеет возможность указать информацию о месторасположении AllSky-камеры. Информация после этого становится доступной на веб-страницах формируемых Системой.

**Comment by oleg-milantiev** [comment]
Сделал таблицу настроек, буду пополнять её

**Comment by oleg-milantiev** [comment]
Добавил Настройки / Обсерватория.
Там поля долгота / широта и timezone.
