### ISSUE TITLE
"Листание" кадров

### ISSUE THREAD

**Issue by avfc1874** [oleg-milantiev/allsky.py#35]
Для оперативной оценки динамики изменения неба должна быть возможность просмотреть предыдущие кадры путем вызова операции "Перейти к предыдущему кадру", а потом вернуться к последнему кадру снятому камерой.

**Comment by oleg-milantiev** [comment]
Причём лучше с клавиатуры. Стрелками (налево-направо, home)

**Comment by avfc1874** [comment]
Конечно использование "горячих" клавиш заслуживает особого внимания.

**Comment by oleg-milantiev** [comment]
Готово

**Comment by avfc1874** [comment]
К сожалению нет "Home" - на последний кадр
