### ISSUE TITLE
"Наклейки" с обозначением сторон горизонта

### ISSUE THREAD

**Issue by avfc1874** [oleg-milantiev/allsky.py#36]
Желательно иметь возможность в глобальных настройках указать расположение наклеек с-ю-в-з, которые будут сохраняться на кадре.

**Comment by oleg-milantiev** [comment]
азимут севера, видимо. Остальные по 90°... или лучше каждую регулировать? Это может понадобиться, если камера установлена не точно вертикально.

**Comment by avfc1874** [comment]
В первой версии думаю достаточно будет первого варианта.

**Comment by oleg-milantiev** [comment]
Буквы сторон света теперь можно реализовать через config.timestamp, пример тут: https://github.com/oleg-milantiev/allsky.py/blob/master/config.py.dist:16

Нужно добавить 4 аналогичных блока NWES

**Comment by oleg-milantiev** [comment]
https://github.com/oleg-milantiev/allsky.py/blob/master/config.py.dist , строка 16

**Comment by avfc1874** [comment]
Требуется ли после внесения параметров config-файл делать Reboot ОС на Миникомпе?

**Comment by oleg-milantiev** [comment]
Достаточно перезапуска allsky-демона:
https://github.com/oleg-milantiev/allsky.py/wiki/daemon - внизу
