### ISSUE TITLE
Автоматическое формирование файла Кеограмма

### ISSUE THREAD

**Issue by avfc1874** [oleg-milantiev/allsky.py#37]
Один раз в сутки требуется формировать файл Кеограммы.

**Comment by oleg-milantiev** [comment]
Расскажи подробней, что за зверь такой

**Comment by avfc1874** [comment]
Вот здесь "подглядел"
https://github.com/thomasjacquin/allsky#keograms

**Comment by avfc1874** [comment]
Эта фишка чисто "бантик", который не сильно влияет на концептуальные бизнес-потребности.

**Comment by oleg-milantiev** [comment]
Ух ты! Класс.
Хочу :)

**Comment by oleg-milantiev** [comment]
> Эта фишка чисто "бантик", который не сильно влияет на концептуальные бизнес-потребности.

Что ж, такой milestone и назначим :)

**Comment by oleg-milantiev** [comment]
Готово в целом. Есть запланированные улучшения. В других задачах
