### ISSUE TITLE
%% облачности

### ISSUE THREAD

**Issue by oleg-milantiev** [oleg-milantiev/allsky.py#38]
Детектирование звёзд.
v1 - хотя бы просто посчитать количество шариков на снимке и по нему косвенно понимать %% ясного неба.

**Comment by avfc1874** [comment]
Интересная возможность!

**Comment by oleg-milantiev** [comment]
https://astronomy.ru/forum/index.php/topic,149680.msg4699036.html#msg4699036

**Comment by oleg-milantiev** [comment]
Решено. Звёзды теперь в аннотации и в графике.
