### ISSUE TITLE
Настройка - Периодичность получения данных с Датчиков и записи их в Базу

### ISSUE THREAD

**Issue by avfc1874** [oleg-milantiev/allsky.py#39]
Должна быть возможность указать в Настройках "Периодичность (сек)" автоматического получения данных с датчиков и их записи в Базу.

**Comment by oleg-milantiev** [comment]
Я оптимизировал базу. Малина сможет лет 5+ записывать данные раз в минуту с десятка датчиков.
Думаешь, может понадобится более частая / редкая запись значений?

**Comment by avfc1874** [comment]
Предлагаю этот запрос перевести в статус "Закрыт".

**Comment by avfc1874** [comment]
Закрыт. В настоящее время запрос неактуальный.
