### ISSUE TITLE
Генерить мультик за час

### ISSUE THREAD

**Issue by oleg-milantiev** [oleg-milantiev/allsky.py#4]
Т.к. ресурсоёмкая задача для мелкой малины, то генерить мультик по запросу пользователя. 
Скорее всего, асинхронно. То есть в фоне.

**Comment by avfc1874** [comment]
В конфигурационном файле желательно иметь возможность установить параметр "Количество кадров в секунду" Значение по-умолчанию = 2

**Comment by oleg-milantiev** [comment]
Сделал.
Сейчас есть только за час. Но возможности шире.

Нужно проверить соответствие времени. Возможен сдвиг на 3 часа (UTC вместо МСК)

**Comment by oleg-milantiev** [comment]
да. Сдвиг был. Устранил

**Comment by avfc1874** [comment]
Может будет здорово, если Мультик за час будет продолжительностью 1 мин, т.е. 1 сек = 1 мин реального времени?

**Comment by oleg-milantiev** [comment]
1 минута = 60 сек. То есть 1fps? Очень медленно для тебя, но норм для тебя - значит нужно дать возможность настраивать частоту кадров.
