### ISSUE TITLE
Восстановить иконки в навигаторе страниц

### ISSUE THREAD

**Issue by avfc1874** [oleg-milantiev/allsky.py#42]
Бантик.
Восстановить иконки в навигаторе страниц при выборе "Сейчас" и "Архив"
В настоящее время иконки имеются только при выборе страницы "Графики"

![изображение](https://user-images.githubusercontent.com/34251661/54835128-9baa8e80-4cd2-11e9-8dab-f8ac5cc58c21.png)

**Comment by oleg-milantiev** [comment]
Разобрался. Починил

**Comment by avfc1874** [comment]
Спасибо!
