### ISSUE TITLE
Сохранять в базу выдержку и среднее. Другие данные по снимку

### ISSUE THREAD

**Issue by oleg-milantiev** [oleg-milantiev/allsky.py#43]
Пригодится. Включить данные в показ графиков

**Comment by oleg-milantiev** [comment]
Сохранил и вывел в веб

**Comment by avfc1874** [comment]
Спасибо!

**Comment by avfc1874** [comment]
Очень полезные данные! В частности для прогнозирования действий в ходе астросессии.
