### ISSUE TITLE
Архив - переход к времени

### ISSUE THREAD

**Issue by oleg-milantiev** [oleg-milantiev/allsky.py#44]
Сейчас можно листать кадры. Но если нужно много отлистать, то лучше ниже снимка добавить инструмент перехода к времени снимка. Удобней будет, мне кажется, в виде графика выдержки, например.
А для этого выдержку нужно сохранять: https://github.com/oleg-milantiev/allsky.py/issues/43

**Comment by avfc1874** [comment]
Т.е. На графике, который отображает CCD Выдержка будет возможность выбрать временную метку и открыть соответствующий кадр?

**Comment by oleg-milantiev** [comment]
Ага, был такой план.
Думаю, как лучше реализовать

**Comment by avfc1874** [comment]
Открывается кадр для выбранной позиции. Имеются кнопки Назад - Вперёд с возможностью навигации.

**Comment by oleg-milantiev** [comment]
Реализовал в разделе "Графики".
Если выбраны CCD* показатели, то клик на точку на графике открывает новую вкладку с архивом, перемотанным на указанную дату.
В графиках сделал о том подпись (под графиком).

**Comment by avfc1874** [comment]
Спасибо!
Очень полезная возможность реализована.

**Comment by Baker1977** [comment]
Кстати было бы не плохо, если на картинках и на видео писались дата и время

**Comment by avfc1874** [comment]
Заслуживает внимания. Лучше к.м.к. оформить это отдельным запросом.

**Comment by Baker1977** [comment]
Кстати не очень удобно мне кажется через график на конкретный снимок попадать... эту функцию надо сделать в "Архиве"
