### ISSUE TITLE
BUG - Видеоролик созданный системой невозможно открыть медиаплеером

### ISSUE THREAD

**Issue by avfc1874** [oleg-milantiev/allsky.py#50]
Созданный файл 2019-03-27-240p.mp4 невозможно открыть медиаплеером и его просмотреть.

**Comment by avfc1874** [comment]
Скачал на локальный диск.
Попытка открыть файл для просмотра медиаплеерами WinAmp, Windows Media Player закончились неудачей. Ранее WinAmp успешно использовался для открытия и просмотра файлов полученных из Системы.

**Comment by oleg-milantiev** [comment]
Там mp4, если не ошибаюсь.
Я проигрываю его в VLC. Другими плеерами не пробовал

**Comment by avfc1874** [comment]
> 
> 
> Там mp4, если не ошибаюсь.
> Я проигрываю его в VLC. Другими плеерами не пробовал

Странно. Я использую WinAmp с установленной вместе с ним богатой коллекцией видео и аудиокодеков. Этим же плеером вчера смотрел видео предыдущих суток. Пока предлагаю ничего не трогать. Может на ОС рабочего ноута накатили корпоративное обновление? Попробую вечером этот видеоролик открыть дома.

**Comment by oleg-milantiev** [comment]
Подтверждаю проблему с ЧБ-роликом на андроиде в хроме.

**Comment by avfc1874** [comment]
На компе с ОС Windows аналогичная ситуация. Последние ролики (начиная с 27.03.2019) невозможно просмотреть после их скачивания или плеером, встроенным в браузер.

**Comment by avfc1874** [comment]
Спасибо! Исправлено.
