### ISSUE TITLE
Поддержка платки реле

### ISSUE THREAD

**Issue by oleg-milantiev** [oleg-milantiev/allsky.py#53]
4 канала норм. Мало ли для чего пригодится владельцу обсерватории.
Сделать просто, а потенциальная польза огромная

**Comment by oleg-milantiev** [comment]
Сделал набросок веб-части. Расширил конфиг.

**Comment by avfc1874** [comment]
Вероятно эта страница будет доступна только после входа в качестве Администратора?

**Comment by oleg-milantiev** [comment]
Точно! Сейчас спрячу её. Будет только после авторизации. Пока единственный юзер - админ

**Comment by oleg-milantiev** [comment]
Сделал

**Comment by oleg-milantiev** [comment]
Решено
