### ISSUE TITLE
Удалять старые видео

### ISSUE THREAD

**Issue by oleg-milantiev** [oleg-milantiev/allsky.py#56]
Плюс настройка сколько дней хранить.

**Comment by avfc1874** [comment]
Предлагается значение по-умолчанию "Хранить видео"=30 дней

**Comment by oleg-milantiev** [comment]
Готово. Настройка пока в конфиге
https://github.com/oleg-milantiev/allsky.py/blob/master/config.py.dist

Секция video

**Comment by avfc1874** [comment]
Следует ли понимать, что (!) каждый день (по-расписанию) производится удаление файла видео срок хранения, которого превышен?

**Comment by oleg-milantiev** [comment]
Создаётся новый ролик и, аналогично удалению старых jpg из snap-архива, удаляется старый mp4 из папки video
