### ISSUE TITLE
Страница "О системе"

### ISSUE THREAD

**Issue by avfc1874** [oleg-milantiev/allsky.py#58]
Желательно иметь возможность просмотра информации о Системе на отдельной странице.
Кроме информации о текущей версии программе и текущих характеристиках микрокомпьютера формируемых Системой автоматически. Администратор имеет возможность в виде текста указать состав используемого другого оборудования, дату ввода в эксплуатацию, при необходимости месторасположение.

**Comment by oleg-milantiev** [comment]
Поглощено https://github.com/oleg-milantiev/allsky.py/issues/26
