### ISSUE TITLE
BUG - После загрузки ОС Миникомпа - Операция изменения статуса реле закончилась неудачей

### ISSUE THREAD

**Issue by avfc1874** [oleg-milantiev/allsky.py#60]
![изображение](https://user-images.githubusercontent.com/34251661/55876455-5de9a900-5ba0-11e9-9b5c-e67d6edcd121.png)

После восстановления электропитания Миникомпа и загрузки на нем ОС, отображаемое состояние Реле на соответствует. Операция изменения статуса закончилась неудачей

**Comment by oleg-milantiev** [comment]
Решено
