### ISSUE TITLE
Превьюхи кеограмм

### ISSUE THREAD

**Issue by oleg-milantiev** [oleg-milantiev/allsky.py#67]
что в перспективе лучше как фотоальбом сделать - с мелкой превьюхой. Клик по ней, а не по имени, как сейчас.

**Comment by oleg-milantiev** [comment]
Оживить генерацию keo в рамках Docker сборки

**Comment by oleg-milantiev** [comment]
Готово:
- Оживить генерацию keo в рамках Docker сборки

**Comment by oleg-milantiev** [comment]
![image](https://github.com/oleg-milantiev/allsky.py/assets/15366972/a50af58c-adb7-408c-9944-3e1f4450e6e2)

**Comment by avfc1874** [comment]
Эта хорошая возможность!
