### ISSUE TITLE
Кеограмма - Автоматический анализ для формирования статистики "Хорошие ночи"

### ISSUE THREAD

**Issue by avfc1874** [oleg-milantiev/allsky.py#69]
Желательно.
Реализовать алгоритм оценки файла Кеограмма для получения информации и формирования статистических данных "Хорошие ночи".

**Comment by oleg-milantiev** [comment]
Мне кажется, для этой оценки достаточно цифровых данных по выдержке / среднему в течение ночей. Их и обработать проще.

**Comment by avfc1874** [comment]
Точно! Ты прав и запрос для оценки %% уже есть.

**Comment by avfc1874** [comment]
Запрос закрыл как неактуальный.
