### ISSUE TITLE
Конфигурация - Учесть коректность отображения времени с учетом развертывания системы в разных часовых поясах

### ISSUE THREAD

**Issue by avfc1874** [oleg-milantiev/allsky.py#70]
Весьма важно предусмотреть конфигурирование и корректное отображение времени с учетом того, что система может быть развернута в другом (нежели МСК) часовом поясе.

**Comment by oleg-milantiev** [comment]
Это решается корректной настройкой timezone в самой малине. Для данного ПО не существенно, в какой зоне он работает. Будет показывать локальное время.

**Comment by avfc1874** [comment]
Понял. Спасибо!
