### ISSUE TITLE
Автоудаление файла кадра объёма 0 байт

### ISSUE THREAD

**Issue by avfc1874** [oleg-milantiev/allsky.py#71]
Требуется выполнять проверку и удалять "битые" файлы, у которых объем 0 байт перед формированием видео или Кеограммы.

**Comment by oleg-milantiev** [comment]
О, а откуда такой пустой взялся, интересно...
2019-04-20_17-01.jpg одного у тебя нашёл.

В момент записи файла вырубился комп?

**Comment by avfc1874** [comment]
Сбой в электропитания Малины.

**Comment by oleg-milantiev** [comment]
Добавил в ежедневное формирование видео
