### ISSUE TITLE
Кеограммы - Возможность просмотра путем "листания" файлов

### ISSUE THREAD

**Issue by avfc1874** [oleg-milantiev/allsky.py#75]
Желательно для созданных системой файлов Кеограмм реализовать возможность их просмотра в виде альбома путем "листания".

**Comment by oleg-milantiev** [comment]
... с календарём, как в архиве.

**Comment by oleg-milantiev** [comment]
Решено в рамках https://github.com/oleg-milantiev/allsky.py/issues/67

Кликаем на любую keo и дальше стрелками в lightbox
