### ISSUE TITLE
BUG - Список кадров - Невозможно просмотреть Архив

### ISSUE THREAD

**Issue by avfc1874** [oleg-milantiev/allsky.py#77]
Во вложении скрины.
![изображение](https://user-images.githubusercontent.com/34251661/57676864-29995a80-762e-11e9-9d7a-6831dd208202.png)
![изображение](https://user-images.githubusercontent.com/34251661/57676895-3a49d080-762e-11e9-83ea-7ddb5a80067a.png)

**Comment by oleg-milantiev** [comment]
Проверили. Не актуально
