### ISSUE TITLE
Сенсоры - Отображение текущих значений T/H/P под Главным меню

### ISSUE THREAD

**Issue by avfc1874** [oleg-milantiev/allsky.py#81]
Обеспечить под Главным меню отображение текущих значений T/H/P для каждого сенсора, подключенного к системе.

**Comment by oleg-milantiev** [comment]
Ввёл в config.py массив sensors. В нём перечислены все сенсоры, подключенные к миникомпу.
Сейчас там только bme280. Перечислены каналы этого сенсора. У тебя, например, это 0 и 1.

Вывел в веб показания всех перечисленных в конфиге сенсоров.

**Comment by avfc1874** [comment]
> 
> 
> Ввёл в config.py массив sensors. В нём перечислены все сенсоры, подключенные к миникомпу.
> Сейчас там только bme280. Перечислены каналы этого сенсора. У тебя, например, это 0 и 1.
> 
> Вывел в веб показания всех перечисленных в конфиге сенсоров.

Отлично!
