### ISSUE TITLE
Конфигурация - "Название сенсора"

### ISSUE THREAD

**Issue by avfc1874** [oleg-milantiev/allsky.py#82]
Система должна обеспечить возможность указать в файле конфигурации "Название" для сенсоров, которые к ней подключены. В последующем это свойство используется для идентификации данных для хранения и отображения информации на веб-страницах.

**Comment by oleg-milantiev** [comment]
Готово. Пример

sensors = {
	'bme280': {					# Два датчика BME280. 0 и 1
		0: 'Купол',
		1: 'Улица'
	}
}

**Comment by avfc1874** [comment]
> 
> 
> Готово. Пример
> 
> sensors = {
> 'bme280': { # Два датчика BME280. 0 и 1
> 0: 'Купол',
> 1: 'Улица'
> }
> }

Спасибо!
