### ISSUE TITLE
API - Обработка и предоставление по запросу данных о последних значениях T/H/P

### ISSUE THREAD

**Issue by avfc1874** [oleg-milantiev/allsky.py#84]
Требуется обеспечить возможность обработки запроса внешнего программного приложения на получение последних значений T/H/P сенсоров, которые подключены к Системе.

**Comment by avfc1874** [comment]
В качестве ответа предлагается формировать файл формата XML, следующего содержания:
`<?xml version="1.0" encoding="utf-8" ?>
<sensors last_update="04.11.2019 15:18:34">
  <sensor sensor_id="1" sensor_name="Под куполом AllSky">
    <param name="temperature" unit="°C" value="14.3" />
    <param name="pressure" unit="мм рт.ст." value="749.4" />
    <param name="humidity" unit="%" value="62" />
  </sensor>
  <sensor sensor_id="2" sensor_name="Снаружи">
    <param name="temperature" unit="°C" value="5.1" />
    <param name="pressure" unit="мм рт.ст." value="749.1" />
    <param name="humidity" unit="%" value="81" />
  </sensor>
</sensors >`

**Comment by oleg-milantiev** [comment]
Не, будет JSON для унификации (т.к. он уже применяется в проекте).

**Comment by avfc1874** [comment]
> Не, будет JSON для унификации (т.к. он уже применяется в проекте).
Спасибо! Хорошо.

**Comment by oleg-milantiev** [comment]
Готово. Описал в документации: https://github.com/oleg-milantiev/allsky.py/wiki/web-REST

**Comment by avfc1874** [comment]
> 
> 
> Готово. Описал в документации: https://github.com/oleg-milantiev/allsky.py/wiki/web-REST

Отлично! Спасибо большое!
