### ISSUE TITLE
Сконфигурировать в config.py вывод на изображение значений сенсоров T/H/P

### ISSUE THREAD

**Issue by avfc1874** [oleg-milantiev/allsky.py#85]
Желательно иметь возможность в файле конфигурации config.py указать координаты X, Y, размер шрифта и цвет текста для вывода на формируемое изображение значений T/H/P сенсоров, подключенных к системе.

**Comment by oleg-milantiev** [comment]
Сейчас аннотации ушли в веб (настройки / обработка). Нужно будет добавить там анотацию данных датчиков.
