### ISSUE TITLE
Реализация алгоритмов оптимизации объемов хранения данных сенсоров

### ISSUE THREAD

**Issue by avfc1874** [oleg-milantiev/allsky.py#91]
Весьма желательно реализовать периодический (1 раз в сутки) запуск операций по оптимизации объемов хранения данных, которые были получены от подключенных сенсоров.

Предлагается:
- записи старше 1 месяца удалять;
- для записей старше одной недели сохранять по одной записи каждого часа, а остальные удалять.
- для записей старше одного дня, но менее 7 дней сохранять по 10 записей каждого часа.

**Comment by oleg-milantiev** [comment]
Решено в рамках настройки архива (кол-во дней хранения).
Удаление ежечасно в watchdog.py
