### ISSUE TITLE
Управление настройками камеры из веб

### ISSUE THREAD

**Issue by oleg-milantiev** [oleg-milantiev/allsky.py#92]
Перенести настройки камеры из config.py в веб-интерфейс. Чтобы можно было покрутить и посмотреть, что получится. Обязательно с кнопкой возврата к начальным.

**Comment by flyeye** [comment]
#96  - входит в эту задачу.

**Comment by avfc1874** [comment]
> Обязательно с кнопкой возврата к начальным.

Это весьма полезная возможность!

**Comment by oleg-milantiev** [comment]
Есть польза в текстовике config.py. Он, с точки зрения бритвы Оккама, максимально независем от внешних зависимостей. Но, конечно, если вспомнить многочисленные интерфейсы роутеров, ip-камер и другого современного сетевого оборудования, все настройки, так или иначе, должны присутствовать в вебе.

Тогда нужно ВСЕ настройки переносить в веб. Не только какие-то отдельные оставлять в config.py, а какие-то в вебе. Недавно вспомненный Оккам призывает за хранение всех настроек только в одном месте. Видимо, в вебе.

**Comment by oleg-milantiev** [comment]
Начал переработку веба

![image](https://user-images.githubusercontent.com/15366972/231721057-b83e8453-3ad9-46d4-b627-4f509074140e.png)

По её готовности уберу config.py вовсе. Все настройки будут храниться в базе.

**Comment by avfc1874** [comment]
Понятный интерфейс формы "Настройки"

**Comment by oleg-milantiev** [comment]
Уф... большой объём изменений.
Пока что собрал веб. Ещё не сохраняет. И пользователей пока не редактирует.

Изучите плиз, вдруг будут какие замечания. Лучше внести корректировки сейчас, если таковые будут.

https://youtu.be/YJ9sL9--D4w

**Comment by avfc1874** [comment]
> Уф... большой объём изменений. Пока что собрал веб. Ещё не сохраняет. И пользователей пока не редактирует.
> 
> Изучите плиз, вдруг будут какие замечания. Лучше внести корректировки сейчас, если таковые будут.
> 
> https://youtu.be/YJ9sL9--D4w

Здоровски! Понятный интерфейс. Название используемой камеры нужно знать, чтобы драйвера корректно под нее "подхватились" или будет достаточно выбора значения из комбобокса?
Может имеет смысл на вкладке Архив установить периодичность очистки данных?

**Comment by oleg-milantiev** [comment]
> Название используемой камеры нужно знать, чтобы драйвера корректно под нее
> "подхватились" или будет достаточно выбора значения из комбобокса?

На первом этапе через запуск /opt/allsky.py/list.py вручную.
Хочется нарезать фичи покороче. Иначе есть риск захлебнуться и долго браться за доделку.
Она и сейчас достаточно обширна. Однозначно, лучше выносить всё в отдельные issue.

> Может имеет смысл на вкладке Архив установить периодичность очистки данных?

Ага, так и есть сейчас
![image](https://user-images.githubusercontent.com/15366972/234084856-40b3d1fd-0368-434e-83d2-6f3795c15c2e.png)

**Comment by oleg-milantiev** [comment]
Веб готов.
Всё сохраняется в базе в JSON.

Осталось использовать сохранённое в allsky.py

**Comment by oleg-milantiev** [comment]
Добавил использование в allsky.py. Случайно в master залил. В следующий раз буду в develop лить. А пока можно начинать тестирвать из master.

Чуть поломал allsky.py в части регулировки обогрева. Хочу вынести это в отдельный скрипт. Пока что под управлением supervisord. В перспективе в docker.
