### ISSUE TITLE
Переход на заданную дату и время

### ISSUE THREAD

**Issue by flyeye** [oleg-milantiev/allsky.py#94]
Часто бывает нужно посмотреть что было ночью в определенное время. Хочется иметь возможность ввести и дату и время и сразу перепрыгнуть на соответствующий снимок, а не листать.

**Comment by flyeye** [comment]
Пожалуй для меня эта фича сейчас самая востребованная. Не обязательно делать прямо ввод даты времени, можно добавить стрелочки >>  и <<, которые будут пролистывать час, и <<<, >>> которые будут пролистывать сутки. Или вставить 24-ую шкалу  в виде линей где-то сверху или снизу. Выбор даты можно сделать стандартным контролом. В общем, можно сделать максимально просто.

**Comment by avfc1874** [comment]
> 

Думаю, что использование элемента UI "Календарь" будет удобнее пользователю для навигации.

**Comment by oleg-milantiev** [comment]
Ага. Сам думал о подобном. Модуль показа сейчас в зачаточном состоянии. Будем развивать!

**Comment by oleg-milantiev** [comment]
![image](https://user-images.githubusercontent.com/15366972/230726003-a708f3fa-72dd-4c62-8f1c-0a67d60513b4.png)

**Comment by flyeye** [comment]
Протестировал, работает! Спасибо!
