### ISSUE TITLE
Настройка avgMin и avgMax через веб-интерфейс

### ISSUE THREAD

**Issue by flyeye** [oleg-milantiev/allsky.py#96]
В процессе настройки камеры эти параметры приходится менять довольно часто (несколько раз в день) в течении длительного времени (недели) подбирая наиболее удачные параметры. Днем подправишь - ночью темно, ночью подправишь - днем перегорает, и т.д. Процесс итерационный. Новая камера, новый объектив - все заново... 
Каждый раз нужно подключаться по SSH. Было бы удобно это делать через веб-интерфейс. Более того, тогда бы это можно бы кому-то поручить, а не делать самому.

**Comment by oleg-milantiev** [comment]
Задача поглащена https://github.com/oleg-milantiev/allsky.py/issues/92
