### ISSUE TITLE
Новые зависимости 

### ISSUE THREAD

**Issue by flyeye** [oleg-milantiev/allsky.py#98]
Import requests - требует инсталляции соответствующего пакета
Баланс белого требует установки opencv-contrib-python

Может быть еще что-то всплывет. Как минимум стоит иметь ввиду перед обновлением старых инсталляций.

**Comment by oleg-milantiev** [comment]
Потеряло актуальность при переходе в докер. Image содержит и request, и все необходимые пакеты. Если чего не хватает, добавим и пересоберём!

(необходимо тестирование и новые issue)
